const adminModules = {
  gestionUsuarios: {
    name: "Gestión de Usuarios",
    description: "Administración de usuarios y roles.",
    icon: "👤",
    path: "/admin/gestion-usuarios",
    roles: ["admin"],
    category: "administracion",
    badge: { label: "Nuevo", color: "blue" },
  },
  gestionEmpresas: {
    name: "Gestión de Empresas",
    description: "Gestión de datos de empresas.",
    icon: "🏢",
    path: "/admin/gestion-empresas",
    roles: ["admin"],
    category: "administracion",
  },
  contratosServicios: {
    name: "Contratos y Servicios",
    description: "Gestión de contratos y servicios.",
    icon: "🧳",
    path: "/admin/contratos-servicios",
    roles: ["admin"],
    category: "administracion",
  },
  gestionServicios: {
    name: "Administrar Servicios",
    description: "Creación y configuración de servicios.",
    icon: "🛎️",
    path: "/admin/gestion-servicios",
    roles: ["admin"],
    category: "administracion",
  },
  gestionCredenciales: {
    name: "Administrar Credenciales",
    description: "Storage de credenciales.",
    icon: "🪪",
    path: "/admin/gestion-credenciales",
    roles: ["admin"],
    category: "administracion",
  },
  gestionDocumentos: {
    name: "Administrar Documentos",
    description: "Administrar poderes, RUT electrónicos, etc.",
    icon: "📑",
    path: "/admin/gestion-documentos",
    roles: ["admin", "trabajador"],
    category: "administracion",
  },
  gestionComisiones: {
    name: "Administrar Comisiones",
    description: "Hub de comisiones: tramos y resumen mensual.",
    icon: "💵",
    path: "/admin/comisiones",
    roles: ["admin", "trabajador"],
    category: "administracion",
  },
  empresaCorreos: {
    name: "Correos por Empresa",
    description: "Asigna y gestiona correos de facturación, cobranza y notificación por empresa.",
    icon: "✉️",
    path: "/admin/empresa-correos",
    roles: ["admin"],
    category: "administracion",
  },
  usuariosActivos: {
    name: "Usuarios Activos",
    description: "Monitorea sesiones activas y desconecta usuarios.",
    icon: "🟢",
    path: "/admin/usuarios-activos",
    roles: ["admin"],
    category: "administracion",
    badge: { label: "Nuevo", color: "green" },
  },
  historialConexiones: {
    name: "Historial de Conexiones",
    description: "Historial global de sesiones y última actividad.",
    icon: "🕒",
    path: "/admin/historial-conexiones",
    roles: ["admin"],
    category: "administracion",
    badge: { label: "Nuevo", color: "blue" },
  },
};

export default adminModules;
