import {
  RiApps2Line,
  RiUser3Line,
  RiSettings4Line,
  RiLogoutBoxRLine,
  RiFileExcelLine,
  RiFileChartLine,
  RiArticleLine,
  RiUserHeartLine,
  RiBankLine,
  RiWallet3Line,
  RiMoneyDollarBoxLine,
  RiHospitalLine,
  RiCustomerService2Line,
  RiBookOpenLine,
  RiQuestionAnswerLine,
  RiMailLine,
  RiErrorWarningLine,
  RiUserSettingsLine,
  RiServiceLine,
  RiBuilding4Line,
  RiSettings3Line,
  RiDashboardLine,
  RiDatabase2Line,
  RiShieldKeyholeLine,
  RiFileList3Line,
  RiHome8Line,
  RiScalesLine,
  RiFootprintLine
} from "@remixicon/react";

const menuItems = [
  {
    name: "Inicio",
    href: "/dashboard",
    icon: RiApps2Line,
    roles: ["admin", "trabajador", "empresa", "cliente", "trabajador"],
  },
  {
    category: "Servicios",
    items: [
      {
        name: "Moras Presuntas",
        description: "Administra y revisa los detalles de tus moras presuntas.",
        href: "/dashboard/mora-presunta",
        icon: RiArticleLine,
        roles: ["admin", "trabajador", "cliente"],
      },
      {
        name: "Pagos en exceso",
        description: "Gestiona y verifica los pagos en exceso recuperados.",
        href: "/servicios/pagex",
        icon: RiWallet3Line,
        roles: ["admin", "trabajador", "cliente"],
      },
      {
        name: "Licencias Médicas",
        description: "Administra los subsidios por licencias médicas.",
        href: "/dashboard/licencia-medica",
        icon: RiHospitalLine,
        roles: ["admin", "trabajador", "cliente", "trabajador"],
      },
      {
        name: "Pagos Previsionales",
        description: "Supervisa los pagos previsionales de manera eficiente.",
        href: "/servicios/pagos-previsionales",
        icon: RiMoneyDollarBoxLine,
        roles: ["admin", "trabajador", "cliente"],
      },
      {
        name: "Cargas Familiares",
        description: "Gestiona las cargas familiares.",
        href: "/servicios/cargas-familiares",
        icon: RiUserHeartLine,
        roles: ["admin", "trabajador", "cliente", "trabajador"],
      },
      {
        name: "Depósitos Convenidos",
        description: "Administra depósitos convenidos con precisión.",
        href: "/servicios/depositos-convenidos",
        icon: RiBankLine,
        roles: ["admin", "trabajador", "cliente"],
      },
      {
        name: "Visitas Domiciliarias",
        description: "Revisa el estado de tus visitas.",
        href: "/dashboard/visitas-domiciliarias",
        icon: RiHome8Line,
        roles: ["admin", "trabajador", "cliente", "supervisor"],
      },
      {
        name: "Mis Visitas",
        description: "Completa las visitas asignadas en terreno.",
        href: "/mis-visitas",
        icon: RiFootprintLine,
        roles: ["trabajador", "admin", "supervisor"],
      },
      {
        name: "Ficha del Trabajador",
        description: "Visualiza el estado consolidado por RUT.",
        href: "/servicios/ficha-trabajador",
        icon: RiFileList3Line,
        roles: ["admin", "trabajador", "cliente", "empresa"],
      },
      {
        name: "Conciliación",
        description: "Carga y valida pagos de anticipos y subsidios.",
        href: "/servicios/conciliacion",
        icon: RiScalesLine, // <-- Ícono para el nuevo módulo
        roles: ["admin", "trabajador"], // Roles que pueden verlo
      },
    ],
  },
  {
    category: "Herramientas",
    items: [
       {
        name: "Indicadores Previsionales",
        description: "Revisa los ultimos indicadores Previsionales.",
        href: "/indicadores-previsionales",
        icon: RiArticleLine,
        roles: ["admin", "trabajador", "empresa"],
      },
      {
        name: "Licencias Médicas",
        description: "Convierte licencias médicas a digital.",
        href: "/transformar-licencias",
        icon: RiArticleLine,
        roles: ["admin", "trabajador", "empresa"],
      },
      {
        name: "Pagos en Exceso",
        description: "Analiza de forma automatica las planillas de Previred.",
        href: "/procesar-pagex",
        icon: RiArticleLine,
        roles: ["admin", "trabajador", "empresa"],
      },
      {
        name: "Certificados de Deuda",
        description: "Convierte certificados de deuda de PDF a Excel.",
        href: "/transformar-certificados",
        icon: RiFileChartLine,
        roles: ["admin", "trabajador", "empresa"],
      },
      {
        name: "Comparar Archivos",
        description: "Compara diferencias entre archivos.",
        href: "/comparar-archivos",
        icon: RiFileExcelLine,
        roles: ["admin", "trabajador", "empresa"],
      },
    ],
  },
  {
    category: "Ayuda",
    items: [
      {
        name: "Soporte Técnico",
        description: "Obtén asistencia técnica.",
        href: "/soporte-tecnico",
        icon: RiCustomerService2Line,
        roles: ["admin", "trabajador", "user", "trabajador"],
      },
      {
        name: "Documentación",
        description: "Accede a guías y documentación.",
        href: "/documentacion",
        icon: RiBookOpenLine,
        roles: ["admin", "trabajador", "user", "trabajador"],
      },
      {
        name: "Preguntas Frecuentes (FAQ)",
        description: "Encuentra respuestas a preguntas comunes.",
        href: "/preguntas-frecuentes",
        icon: RiQuestionAnswerLine,
        roles: ["admin", "trabajador", "user", "trabajador"],
      },
      {
        name: "Contacto",
        description: "Comunícate con soporte.",
        href: "/contacto",
        icon: RiMailLine,
        roles: ["admin", "trabajador", "user", "trabajador"],
      },
      {
        name: "Reportar un Problema",
        description: "Informa problemas o bugs.",
        href: "/reportar-problema",
        icon: RiErrorWarningLine,
        roles: ["admin", "trabajador", "user", "trabajador"],
      },
    ],
  },
  {
    category: "Administración",
    items: [
      {
        name: "Administración de Usuarios",
        description: "Gestiona subusuarios y permisos del tenant.",
        href: "/client-admin/usuarios",
        icon: RiUserSettingsLine,
        roles: ["cliente_admin"],
      },
      {
        name: "Gestión de Usuarios",
        description: "Administra usuarios y roles.",
        href: "/admin/gestion-usuarios",
        icon: RiUserSettingsLine,
        roles: ["admin"],
      },
      {
        name: "Usuarios Activos",
        description: "Monitorea y desconecta sesiones activas.",
        href: "/admin/usuarios-activos",
        icon: RiShieldKeyholeLine,
        roles: ["admin"],
      },
      {
        name: "Gestión de Servicios",
        description: "Administra los servicios disponibles.",
        href: "/admin/gestion-servicios",
        icon: RiServiceLine,
        roles: ["admin"],
      },
      {
        name: "Gestión de Empresas",
        description: "Administra las empresas registradas.",
        href: "/admin/gestion-empresas",
        icon: RiBuilding4Line,
        roles: ["admin", "trabajador"],
      },
      {
        name: "Asignar Servicios",
        description: "Configura servicios asignados.",
        href: "/admin/asignar-servicios",
        icon: RiSettings3Line,
        roles: ["admin"],
      },
      {
        name: "Producción y Análisis",
        description: "Genera y revisa prefacturas detalladas.",
        href: "/produccion",
        icon: RiFileChartLine,
        roles: ["admin", "trabajador"],
      },
      {
        name: "Pre-factura",
        description: "Supervisa actividades del sistema.",
        href: "/prefactura",
        icon: RiDashboardLine,
        roles: ["admin"],
      },
      {
        name: "Facturación",
        description: "Realiza copias de seguridad.",
        href: "/facturacion",
        icon: RiDatabase2Line,
        roles: ["admin"],
      },
      {
        name: "Credeniales",
        description: "Gestiona políticas de seguridad.",
        href: "/admin/gestion-credenciales",
        icon: RiShieldKeyholeLine,
        roles: ["admin"],
      },
      {
        name: "Documentos",
        description: "Consulta registros del sistema.",
        href: "/admin/gestion-documentos",
        icon: RiFileList3Line,
        roles: ["admin"],
      },
      {
        name: "Correos por Empresa",
        description: "Asigna y gestiona correos por empresa (facturación, cobranza, general).",
        href: "/admin/empresa-correos",
        icon: RiMailLine,
        roles: ["admin"],
      },
    ],
  },
  {
    category: "UserMenu",
    items: [
      {
        name: "Perfil",
        description: "Visualiza y edita tu perfil.",
        href: "/perfil",
        icon: RiUser3Line,
        roles: ["admin", "trabajador", "empresa", "trabajador"],
      },
      {
        name: "Configuración",
        description: "Ajusta configuraciones de tu cuenta.",
        href: "/configuracion",
        icon: RiSettings4Line,
        roles: ["admin", "trabajador", "empresa", "trabajador"],
      },
      {
        name: "Salir",
        description: "Cierra sesión.",
        href: "#",
        icon: RiLogoutBoxRLine,
        roles: ["admin", "trabajador", "empresa", "trabajador"],
      },
    ],
  },
];

export { menuItems };
